name: CI Build

on: push

jobs:
  # build-ubuntu-clang:
  #   name: ubuntu-clang
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:

  # build-ubuntu-clang-asan:
  #   name: ubuntu-clang-asan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         ASAN:

  # build-ubuntu-clang-valgrind:
  #   name: ubuntu-clang-valgrind
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Install valgrind
  #       run: sudo apt install valgrind

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         VALGRIND:

  # build-ubuntu-gcc:
  #   name: ubuntu-gcc
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         CC: gcc

  # build-ubuntu-gcc-asan:
  #   name: ubuntu-gcc-asan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         CC: gcc
  #         ASAN:

  # build-ubuntu-gcc-valgrind:
  #   name: ubuntu-gcc-valgrind
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: sudo apt install nasm

  #     - name: Install valgrind
  #       run: sudo apt install valgrind

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         CC: gcc
  #         VALGRIND:

  # TODO: REMOVE!
  build-foo-clang:
    name: foo-clang
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print clang version
        run: clang --version

      - name: Build
        run: clang foo.c -o foo -Wfatal-errors

      - name: Run
        run: ./foo

  build-foo-gcc:
    name: foo-gcc
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gcc
        run: brew info gcc

      - name: Print gcc version
        run: gcc --version

      - name: Build
        run: gcc foo.c -o foo -Wfatal-errors

      - name: Run
        run: ./foo

  # build-mac-clang:
  #   name: mac-clang
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: brew install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:

  # build-mac-clang-asan:
  #   name: mac-clang-asan
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Clone the grug submodule
  #       run: git submodule update --init

  #     - name: Install nasm
  #       run: brew install nasm

  #     - name: Run the tests
  #       run: ./tests.sh
  #       env:
  #         OLD_LD:
  #         ASAN:
