name: CI Build

on: push

jobs:
  build-ubuntu-clang:
    name: ubuntu-clang
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone the grug submodule
        run: git submodule update --init

      - name: Run the tests
        run: ./tests.sh
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
